# Generated by Django 5.2 on 2025-04-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_delivery_status_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='path/to/default_image.jpg', upload_to='products/'),
        ),
    ]
